// Gallery — real photos from Zunaira's work
// Images served from /public/gallery/

export const workImages = [
  { id: 1,  src: '/gallery/mehndi 1.jpeg',  title: 'Floral Bridal Full Hands',       category: 'Bridal',      tag: 'Bridal' },
  { id: 2,  src: '/gallery/mehndi 2.jpeg',  title: 'Dark Floral Full Hands',         category: 'Bridal',      tag: 'Bridal' },
  { id: 3,  src: '/gallery/mehndi 3.jpeg',  title: 'Floral Bridal Full Hands',        category: 'Bridal',      tag: 'Bridal' },
  { id: 4,  src: '/gallery/mehndi 4.jpeg',  title: 'Rose Floral Pattern',            category: 'Arabic',      tag: 'Arabic' },
  { id: 5,  src: '/gallery/mehndi 5.jpeg',  title: 'Full Sleeve Bridal',             category: 'Bridal',      tag: 'Bridal' },
  { id: 6,  src: '/gallery/mehndi 6.jpeg',  title: 'Single Hand Floral',             category: 'Arabic',      tag: 'Arabic' },
  { id: 7,  src: '/gallery/mehndi 7.jpeg',  title: 'Heart & Floral Pattern',         category: 'Bridal',      tag: 'Bridal' },
  { id: 8,  src: '/gallery/mehndi 8.jpeg',  title: 'Floral Hibiscus Design',         category: 'Arabic',      tag: 'Arabic' },
  { id: 9,  src: '/gallery/mehndi 9.jpeg',  title: 'Custom OK Initials',             category: 'Bridal',      tag: 'Custom' },
  { id: 10, src: '/gallery/mehndi 10.jpeg', title: 'Full Sleeve Dark Bridal',        category: 'Bridal',      tag: 'Bridal' },
  { id: 11, src: '/gallery/mehndi 11.jpeg', title: 'Floral Vine Design',             category: 'Arabic',      tag: 'Arabic' },
  { id: 12, src: '/gallery/mehndi 12.jpeg', title: 'Mandala Full Hand',              category: 'Bridal',      tag: 'Bridal' },
  { id: 13, src: '/gallery/mehndi 13.jpeg', title: 'OK Initials Bridal',             category: 'Bridal',      tag: 'Custom' },
  { id: 14, src: '/gallery/mehndi 14.jpeg', title: 'Maroon Stain Floral',            category: 'Arabic',      tag: 'Arabic' },
  { id: 15, src: '/gallery/mehndi 15.jpeg', title: 'Full Sleeve Bridal',             category: 'Bridal',      tag: 'Bridal' },
  { id: 16, src: '/gallery/mehndi 16.jpeg', title: 'Bridal Feet Design',              category: 'Feet Mehndi', tag: 'Feet' },
  { id: 17, src: '/gallery/mehndi 17.jpeg', title: 'Happy Karwa Chauth',             category: 'Bridal',      tag: 'Custom' },
  { id: 18, src: '/gallery/mehndi 18.jpeg', title: 'Traditional Story Mehndi',       category: 'Bridal',      tag: 'Bridal' },
  { id: 19, src: '/gallery/mehndi 19.jpeg', title: 'Arabic Geometric Design',        category: 'Arabic',      tag: 'Arabic' },
  { id: 20, src: '/gallery/mehndi 20.jpeg', title: 'Full Sleeve Bridal 2',           category: 'Bridal',      tag: 'Bridal' },
  { id: 21, src: '/gallery/mehndi 21.jpeg', title: 'Rose Floral Palms',              category: 'Arabic',      tag: 'Arabic' },
  { id: 22, src: '/gallery/mehndi 22.jpeg', title: 'Indian Bridal Full Hand',        category: 'Bridal',      tag: 'Bridal' },
  { id: 23, src: '/gallery/mehndi 23.jpeg', title: 'Intricate Bridal Design',        category: 'Bridal',      tag: 'Bridal' },
  { id: 24, src: '/gallery/mehndi 24.jpeg', title: 'Floral Arabic Pattern',          category: 'Arabic',      tag: 'Arabic' },
  { id: 25, src: '/gallery/mehndi 25.jpeg', title: 'Full Coverage Bridal',           category: 'Bridal',      tag: 'Bridal' },
  { id: 26, src: '/gallery/mehndi 26.jpeg', title: 'Bridal Full Sleeve',             category: 'Bridal',      tag: 'Bridal' },
  { id: 27, src: '/gallery/mehndi 27.jpeg', title: 'Floral Engagement Design',       category: 'Bridal',      tag: 'Bridal' },
];

export const reviews = [
  {
    id: 1,
    name: 'Happy Client',
    rating: 5,
    text: 'Thank you so much for this wonderful Mehndi ❤️ Love the work done by uh and also the stain 😍 Ur dedication towards work is immensely wonderful ❤️ Also the in details design.. Thanks 🤲',
    tag: 'Worth it !!!!',
    image: '/gallery/mehndi 1.jpeg',
    via: 'WhatsApp',
  },
  {
    id: 2,
    name: 'Priya Sharma',
    rating: 5,
    text: 'Absolutely stunning bridal mehndi! The designs were exactly what I wanted. Zunaira is so talented and professional. Highly recommend!',
    tag: 'Bridal Mehndi',
    image: '/gallery/mehndi 5.jpeg',
    via: 'Google',
  },
  {
    id: 3,
    name: 'Aisha Khan',
    rating: 5,
    text: 'Best mehndi artist in Mumbai! The stain came out so dark and beautiful. Will definitely book again for every occasion.',
    tag: 'Arabic Mehndi',
    image: '/gallery/mehndi 8.jpeg',
    via: 'Instagram',
  },
  {
    id: 4,
    name: 'Fatima Ali',
    rating: 5,
    text: 'Made my wedding day even more special with gorgeous mehndi. The full sleeve design was breathtaking. Thank you Zunaira!',
    tag: 'Bridal Full Sleeve',
    image: '/gallery/mehndi 15.jpeg',
    via: 'WhatsApp',
  },
  {
    id: 5,
    name: 'Sana Patel',
    rating: 5,
    text: 'Beautiful Arabic designs. Very punctual and professional home service. The custom initials design was a lovely touch!',
    tag: 'Custom Design',
    image: '/gallery/mehndi 9.jpeg',
    via: 'Google',
  },
];
